@startuml Deployment Diagram
node "Nginx" {
    [User Interface] --> [Metrics Display]
    [User Interface] --> [Playground]
    [User Interface] --> [Settings]
}

node "Flask Application" {
    [Flask REST API] --> [Service Logic]
}

database "MySQL Database" {
    [Metrics Storage]
}

node "Swagger" {
    [Swagger UI]
}

node "External Data Sources" {
    [Spam Domain List]
    [Mailservers SMTP Response]
    [DNS Records]
    [Internet Assigned Numbers Authority]
}

[Service Logic] --> [External Data Sources] : Fetches Data
[Settings] --> [Flask REST API] : Configures Endpoints
[Playground] --> [Flask REST API] : Tests Features
[Metrics Display] --> [Flask REST API] : Fetches Metrics
[Swagger UI] --> [Flask REST API] : Documentation
[Service Logic] --> [MySQL Database] : Data Persistence
@enduml